---
- name: Configure Shifted Server
  hosts: aws_migration
  become: yes
  tasks:
    - name: Ensure the "Migration" user exists (Simulation)
      user:
        name: muneef_admin
        state: present

    - name: Install necessary tools (Lift and Shift requirements)
      apt:
        name:
          - net-tools
          - rsync
        state: present
        update_cache: yes

    - name: Verify Migration Data
      copy:
        src: ./app_data.txt
        dest: /home/ubuntu/app_data_verified.txt
        owner: ubuntu
        mode: '0644'
